baseURL: https://hanyicheng.net/
languageCode: zh-cn
title: 韩意铖的个人网站
copyright: '&copy;2022 <a href="https://hanwentao.net">韩文弢</a><br><img src="https://counter.hanwentao.net/count/tag.svg?url=https%3A%2F%2Fhanyicheng.net" alt="Hits">'
theme: han
markup:
  defaultMarkdownHandler: pandoc
security:
  exec:
    allow:
      - ^pandoc
