baseURL: https://hanyicheng.net/
languageCode: zh-cn
title: 韩意铖的个人网站
copyright: <a href="https://hanwentao.net">韩文弢</a>
theme: han
markup:
  defaultMarkdownHandler: pandoc
security:
  exec:
    allow:
      - ^pandoc
